### ISSUE TITLE
emmm , webpack 错误不知道怎么解决.

### ISSUE THREAD

**Issue by 625781186** [nature1995/Vue-Django-Shop-Frontend#4]
![image](https://user-images.githubusercontent.com/30521429/81633740-03281e00-9440-11ea-9a40-15a1d7c85591.png)

**Comment by 625781186** [comment]
好像是路径中有感叹号的问题

**Comment by nature1995** [comment]
应该是路径问题，查看下`./src/views/app/app.vue`和`./src/views/app/app.vue`中的模块导入。
